version: '3.8'

services:
  space-frontend:
    build: .
    container_name: sapce-frontend-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
